name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - shell: bash
      run: bun add -g turbo

    - shell: bash
      run: bun install
